Feature/issue 2/add passcode first time
timofeylyadinsky/NewsApp pull request #2
Opened 2023-08-02 11:44 UTC by timofeylyadinsky

add function for first start
use cases
1. check is it first start
2. save user with passcode
3. save user without passcode

2023-08-02 13:09 UTC, MaxSkr-iTechArt requested changes

2023-08-02 13:09 UTC, MaxSkr-iTechArt commented on app/src/main/java/com/example/newsapp/data/dao/UserDao.kt
> +    fun getUser(): List<User>
Since we are supposed to have one user in the DB, I think we can keep a single object as a return value instead of a list.

2023-08-02 13:09 UTC, MaxSkr-iTechArt commented on app/src/main/java/com/example/newsapp/domain/PasscodeUseCase.kt
User cases are supposed to do only one operation (see https://developer.android.com/topic/architecture/domain-layer). It looks like the Use case should be splited into 3 separate Use cases (e.g. IsPasscodeRequiredUseCase, SavePasscodeUseCase, SkipPasscodeUsecase)
Also, use cases must be main-safe. Since we access the DB here, add a dispatcher to the use cases (see https://developer.android.com/topic/architecture/domain-layer#threading)

2023-08-03 08:06 UTC, timofeylyadinsky commented
Change:
1. change return value from list to null variable
2. split use case into 3 classes
3. add dispatchers(default and io) to make function main-safe

2023-08-03 09:18 UTC, MaxSkr-iTechArt commented on app/src/main/java/com/example/newsapp/domain/PasscodeUseCases.kt
> +    private val defaultDispatcher: CoroutineDispatcher = Dispatchers.Default
Let's use IO dispatcher instead for accessing the DB.

2023-08-03 09:18 UTC, MaxSkr-iTechArt commented on app/src/main/java/com/example/newsapp/domain/PasscodeUseCases.kt
> +    ) {
use default AS code formatter (Option-Command-L), optimize imports (Control-Option-O)

2023-08-03 09:39 UTC, MaxSkr-iTechArt approved these changes

2023-08-03 09:40 UTC, merged