Feature/issue 1/UI passcode screen
timofeylyadinsky/NewsApp pull request #4
Opened 2023-08-04 08:04 UTC by timofeylyadinsky

UI for first passcode screen
1. Viewmodel to take information for ui
2. adding dispatcher module for coroutine
3. UI with jetpack compose

2023-08-04 13:21 UTC, MaxSkr-iTechArt requested changes

2023-08-04 13:21 UTC, MaxSkr-iTechArt commented on app/src/main/java/com/example/newsapp/MainActivity.kt
>                  // A surface container using the 'background' color from the theme
you can remove the commented code

2023-08-04 13:21 UTC, MaxSkr-iTechArt commented on app/src/main/java/com/example/newsapp/ui/screen/PasscodeScreen.kt
> +const val MAX_LENGTH = 4;
you can make this private I suppose

2023-08-04 13:21 UTC, MaxSkr-iTechArt commented on app/src/main/java/com/example/newsapp/viewmodel/PasscodeViewModel.kt
> +) : ViewModel() {
you need to introduce a UI state and use it in the composables https://developer.android.com/topic/architecture/ui-layer#expose-ui-state

2023-08-04 13:21 UTC, MaxSkr-iTechArt commented on app/src/main/java/com/example/newsapp/ui/screen/PasscodeScreen.kt
> +) {
consume the UI state introduced in the ViewModel

2023-08-07 10:00 UTC, timofeylyadinsky commented
1. add passcode state to ViewModel and compose

2023-08-08 12:36 UTC, timofeylyadinsky commented
Changes
1. edit view model function
2. edit state class
3. refactor composable function and showing block with information from ui state vm

2023-08-08 14:05 UTC, MaxSkr-iTechArt approved these changes

2023-08-08 19:44 UTC, merged